version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: sylius
      POSTGRES_USER: sylius
      POSTGRES_PASSWORD: sylius
  php:
    image: php:8.2-fpm
    working_dir: /app
    volumes:
      - ./:/app
    depends_on:
      - db
  nginx:
    image: nginx:1.25
    ports:
      - '8080:80'
    volumes:
      - ./:/app
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
