name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['8.2', '8.3']
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
      - run: composer install --prefer-dist
      - run: vendor/bin/phpstan analyse --no-progress
      - run: vendor/bin/phpunit
      - run: vendor/bin/phpcs --standard=PSR12 src tests
